export const mockCameras = [
  {
    id: "CAM_MAIN_01",
    location: "Main Entrance",
    status: "live" as const,
    timestamp: "22:20:16",
    detections: [],
    isWebcam: true, // This camera will use webcam
    fps: 30,
    resolution: "1080p",
    lastActivity: "2s ago",
    temperature: 42,
    uptime: 99.8,
  },
  {
    id: "CAM_02",
    location: "North Entrance",
    status: "live" as const,
    timestamp: "22:20:16",
    videoUrl:
      "https://customer-assets.emergentagent.com/job_84ac10bc-627d-4954-9eca-97e55efbe4bc/artifacts/wd8gbf67_CAM_01_main_gate.mp4",
    type: "mp4",
    detections: [],
    fps: 25,
    resolution: "720p",
    lastActivity: "1s ago",
    temperature: 38,
    uptime: 98.5,
  },
  {
    id: "CAM_03",
    location: "Main Building",
    status: "live" as const,
    timestamp: "22:20:16",
    videoUrl: "https://drive.google.com/file/d/1xNxGJC-sQEvB0xxHx6KuN-dL6zpyWp_T/preview",
    type: "iframe",
    detections: [
      {
        type: "Person",
        confidence: 94,
        x: 150,
        y: 100,
        width: 80,
        height: 120,
        timestamp: "22:20:16",
      },
    ],
    fps: 30,
    resolution: "1080p",
    lastActivity: "3s ago",
    temperature: 41,
    uptime: 99.2,
  },
  {
    id: "CAM_06",
    location: "Academic Block",
    status: "warning" as const,
    timestamp: "22:20:16",
    videoUrl: "https://drive.google.com/file/d/1xNxGJC-sQEvB0xxHx6KuN-dL6zpyWp_T/preview",
    type: "iframe",
    detections: [],
    fps: 20,
    resolution: "720p",
    lastActivity: "5s ago",
    temperature: 45,
    uptime: 95.3,
  },
  {
    id: "CAM_08",
    location: "South Exit",
    status: "live" as const,
    timestamp: "22:20:16",
    videoUrl:
      "https://customer-assets.emergentagent.com/job_84ac10bc-627d-4954-9eca-97e55efbe4bc/artifacts/9yt7klws_CAM_04_back_gate.mp4",
    type: "mp4",
    detections: [
      {
        type: "Person",
        confidence: 89,
        x: 200,
        y: 150,
        width: 70,
        height: 110,
        timestamp: "22:20:16",
      },
    ],
    fps: 25,
    resolution: "1080p",
    lastActivity: "2s ago",
    temperature: 39,
    uptime: 97.8,
  },
  {
    id: "CAM_CAFE_06",
    location: "Cafeteria",
    status: "live" as const,
    timestamp: "22:20:16",
    image: "/placeholder.svg?height=300&width=400&text=Cafeteria",
    detections: [],
    fps: 30,
    resolution: "720p",
    lastActivity: "1s ago",
    temperature: 43,
    uptime: 99.1,
  },
  {
    id: "CAM_LIB_07",
    location: "Library",
    status: "offline" as const,
    timestamp: "22:20:16",
    image: "/placeholder.svg?height=300&width=400&text=Library",
    detections: [],
    fps: 0,
    resolution: "N/A",
    lastActivity: "5m ago",
    temperature: 0,
    uptime: 0,
  },
  {
    id: "CAM_GYM_08",
    location: "Gymnasium",
    status: "live" as const,
    timestamp: "22:20:16",
    image: "/placeholder.svg?height=300&width=400&text=Gymnasium",
    detections: [],
    fps: 25,
    resolution: "1080p",
    lastActivity: "4s ago",
    temperature: 40,
    uptime: 98.7,
  },
]
